# Generated by Django 5.2 on 2025-04-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
