# Generated by Django 5.2 on 2025-04-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_provider_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='currencyexchangerate',
            constraint=models.UniqueConstraint(fields=('from_currency', 'to_currency', 'date'), name='unique_rate_per_date'),
        ),
    ]
